### ISSUE TITLE
No Shading

### ISSUE THREAD

**Issue by kneubehl** [mdbaron42/pyBoxshade#10]
Hi there,

I have tried running pyBoxshade on both the linux and windows pre-compiled binaries with the clustal output of a nucleotide MAFFT alignment. The program loads in the alignment just fine and the text is manipulable (i.e. I can change the font size and sequence characters per line just fine) but there is no shading in the output (nor the preview). The text is also not converted from lowercase to uppercase nor is a consensus line generated when that option is selected (the consensus label is added to the figure but no consensus sequence). I have run the same alignment file on the Boxshade server and it works fine. I wanted to use pyBoxshade to tailor the image better. Any guidance would be appreciated.

**Comment by mdbaron42** [comment]
Sorry you are having problems. Please post the alignment file that is causing the problems and I will try to find out what needs to be done to fix it. I have not observed a problem like you describe, but there is always something new.

**Comment by mdbaron42** [comment]
Just a thought: is it possible that you are thinking of the view of the alignment file in the main window as a preview? It isn't, I'm afraid, it is just a view of the original file, which some people find helpful to remind them of what file they are working with. If you want to see the shading, you have to generate a PNG picture, which opens in a separate window.

**Comment by kneubehl** [comment]
Ended up figuring it out after a lot of trial and error with different aligner outputs and what it came down to was that pyBoxshade is case sensitive. I changed the case of a mafft output file that wasn't working (lowercase) to uppercase and it was fine, change it back to lowercase and no shading. Not sure if that is in the documentation and I missed it.

**Comment by mdbaron42** [comment]
Glad you found the problem. Lower case letters are not IUPAC standard, so I had never used them (or even thought about them), but I should allow for the possibility. The code has now been changed so that all alignments are converted to uppercase when they are loaded, and I will update the binaries when I can.
