### ISSUE TITLE
start up slowly

### ISSUE THREAD

**Issue by AlisaGU** [mdbaron42/pyBoxshade#6]
Hi, 
my system is 
<img width="201" alt="image" src="https://user-images.githubusercontent.com/38097726/105934709-a92dbe00-608b-11eb-841b-c23d198f4b5c.png">

startup has spent a few minutes and the report shows this application is not responding.

**Comment by mdbaron42** [comment]
Thanks for bringing this to my attention. There seems to be a problem between PyQt and BigSur. I don't have a BigSur Mac to test with, but I will update the binaries to the latest PyQt, hopefully that will fix things.

**Comment by AlisaGU** [comment]
It's wise to not to update😭

**Comment by mdbaron42** [comment]
OK, I think I have solved this. I have only been able to test it on a Virtual Machine with Big Sur installed. Could you try on your own machine, please? The new binary is uploaded as v1.1-beta.

**Comment by AlisaGU** [comment]
It's my pleasure.

The latest version works.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/38097726/106070190-edc66180-613e-11eb-9a6e-402a9d4794fa.png">

Thanks for your quick update.

**Comment by mdbaron42** [comment]
Thanks for your help 🙏. I am closing this issue and posting the updated code.
