### ISSUE TITLE
BS_app.py error

### ISSUE THREAD

**Issue by biopig** [mdbaron42/pyBoxshade#8]
when i use the code python
`
C:\Users\Administrator\Desktop\pyBoxshade-master\pyBoxshade-master>python BS_app.py

BS_app.py:154: DeprecationWarning:/ `np.unciode/` is a deprecated alias for /`np.compat.unciode/`. To silence this warning, use /`np.compat.unciode/` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin/ `str/` for which /`np.compat.unciode/` is itself an alias. Doing this wil
l not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use/ `np.str_/` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self.seqs = np.array([[' ', ' '], [' ', ' ']], dtype=np.unicode)
Traceback (most recent call last):
  File "BS_app.py", line 710, in <module>
    mainWin = MainWindow()
  File "BS_app.py", line 154, in __init__
    self.seqs = np.array([[' ', ' '], [' ', ' ']], dtype=np.unicode)
ValueError: invalid literal for int() with base 10: ' '

C:\Users\Administrator\Desktop\pyBoxshade-master\pyBoxshade-master>
`

**Comment by mdbaron42** [comment]
Hi, thanks for bringing this to my attention. Numpy 1.20 only became available on PyPi a few days ago, so I had not yet tried it.
I think this is a fault with numpy 1.20. The pyBoxshade code works fine with numpy 1.19.5. While the use of dtype=np.unicode is deprecated, and I will update the code in the next release, numpy 1.20 should still have accepted the code ("deprecated" always used to mean " is going to be removed", not " will no longer work").
Is there some reason you have to have numpy v 1.20? If not, the best thing is to revert to 1.19.5. 
Or download one of the packaged binaries, which should work. Any reason not to use the Windows binary (I see you are using a Windows machine)?

**Comment by biopig** [comment]
I have another question, why do I get incomplete results. This is true both on the website and locally.

**Comment by mdbaron42** [comment]
If it is true on the web version AND using this version, it sounds as if there is something specific about your alignment file. If you send me the file, I will be happy to test it - it may help me find a bug in the program that I am unaware of. Either post it here or email me at baron<at symbol>bbsrc.ac.uk.
